#!/usr/bin/env bash
#1. Install nginx web server

sudo apt-get -y update

if sudo apt-get -y install nginx; then
    echo -e \
"http {
    root /var/www/school;
    index index.html;
    server {
        listen 80;
        location / {
        }
    }
}
events {
}" > /etc/nginx/nginx.conf

    mkdir -p /var/www/school

    echo "Hello World!" > /var/www/school/index.html

    sudo service nginx start
else
    echo "Failed to install Nginx."
    exit 1
fi
