#!/usr/bin/env bash
#1. Install nginx web server

sudo apt-get -y update

if sudo apt-get -y install nginx; then
    echo -e \
"http {
    root /var/www/;
    index index.html;
    server {
        listen 80;
        location / {
        }
	location /redirect_me {
		 return 307 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
    }
}
events {
}" > /etc/nginx/sites-available/default

    mkdir -p /var/www/

    echo "Hello World!" > /var/www/index.html

    sudo service nginx start
else
    echo "Failed to install Nginx."
    exit 1
fi
