#!/usr/bin/env bash
#1. Install nginx web server
sudo apt-get -y update

if sudo apt-get -y install nginx; then
    sudo echo  -e "
http {
     include /etc/nginx/mime.types;
     default_type application/octet-stream;
     include /etc/nginx/conf.d/*.conf;
     include /etc/nginx/sites-enabled/*;
}
events {}
" | sudo tee /etc/nginx/nginx.conf > /dev/null
    sudo echo  -e "
server {
  listen 80;
    location / {
        root /var/www/;
        index index.html;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}
" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
    sudo mkdir -p /var/www/

    echo "Hello World!" | sudo tee /var/www/index.html > /dev/null
    sudo nginx -s reload
    sudo service nginx start
else
    echo "Failed to install Nginx."
    exit 1
fi
