#!/usr/bin/env bash
#configure server with http header

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
ed -i "s/http {/http {\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/nginx.conf

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart

