#!/usr/bin/env bash
#configure server with http header

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

    sudo echo  -e "
http {
     include /etc/nginx/mime.types;
     default_type application/octet-stream;
     include /etc/nginx/conf.d/*.conf;
     include /etc/nginx/sites-enabled/*;
}
events {}
" | sudo tee /etc/nginx/nginx.conf > /dev/null
    sudo echo  -e
"
server {
  listen 80;
    location / {
        root /var/www/;
        index index.html;
    }
}
" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
    sudo mkdir -p /var/www/
sudo sed -i "s/http {/http {\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/nginx.conf
sudo cat "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart

