#!/usr/bin/env bash
# Install the load balancer


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.backup
sudo echo -e "
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend http_front
   bind *:80
   default_backend http_back

backend http_back
   balance roundrobin
   server 284541-web-01  100.25.34.155:80 check
   server 284541-web-02  100.26.254.146:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
echo -e "\n\nconfigured - Roundrobin On web-01 & web-02"
sudo service haproxy restart
