#!/usr/bin/env bash
#displays the time for 12 hs and 59 ms.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

h=0

while [ $h -le 12 ]
do
  echo "h: $h"
  m=1
  while [ $m -le 59 ]
  do
    echo "$m"
    (( m++ ))
  done
  (( h++ ))
done
