#!/usr/bin/env bash
# Ensure nginx runs as nginx user
pkill apache2
sed -i -e "s/^user .*/user nginx;/" -e "s/80/8080/g" /etc/nginx/nginx.conf /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

